version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./docker/.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - 92:3306
    php:
        build: docker/php7-fpm
        volumes:
            - sf3-sync:/var/www:rw
            - ./docker/logs/symfony:/var/www/var/logs
    nginx:
        build: docker/nginx
        ports:
            - 90:80
        volumes_from:
            - php
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 91:80
        volumes:
            - ./docker/elk/logstash:/etc/logstash
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
volumes:
    sf3-sync:
        external: true
